### ISSUE TITLE
problem with Arabic language

### ISSUE THREAD

**Issue by mohamedahmed1989** [inoerp/inoERP#11] opened 2015-04-30 17:47 UTC
can I find the Arabic language translation file? how can use it as a deafult
i tried to use it and changed code in basics.inc
defined('DEFAULT_LOCALE') ? null : define('DEFAULT_LOCALE', 'ar_SA');
Please provide me with the details to be able to change localization of the system . 
Thank you in advance .

**Comment by inoerp** [comment] 2015-05-01 00:26
You can find the translation file @ locale\ar_SA\LC_MESSAGES.

No need to change any code at the site level. Each user can choose their preferred language and system 'll default to that language after login.

You can choose the language @ user details -> Preference tab

**Comment by mohamedahmed1989** [comment] 2015-05-01 15:16
i changed  user details -> Preference , change to arabic (ar_SA)
is not record in database , open database change it manual to ar_SA
 and default language still english 
Thank you in advance .

**Comment by inoerp** [comment] 2015-05-02 01:29
If the language preference is not saved that means there is some other issue.
are you able to save other data in the user form, If yes that means your database is not up to date.

If you are in a test environment then do a fresh installation from  gitHUB Master

**Comment by mohamedahmed1989** [comment] 2015-05-02 10:33
installation it again from gitHUB master and problem is still 
anthor problem what is admin model ??
how can i add new model or remove model ??

**Comment by inoerp** [comment] 2015-05-02 10:45
What is admin model ?

I have checked and tested with the latest version of gitHUB and the language preference is working fine.
Is the language preference getting saved or not with the latest version ?

**Comment by mohamedahmed1989** [comment] 2015-05-02 11:07
where is admin Module how can i change in it 
can i add new Module or remove Module 
Upload all the files into the web server 
I use it in localhost not in web server Is it be possible cause of the problem  
Thank you in advance .

**Comment by inoerp** [comment] 2015-05-02 11:19
Admin is not a module but a group of some extensions &  modules.
You can check all the modules / extensions by navigating to Admin -> System -> All modules / All extensions.
You can use any webserver as long as you have PHP 5.5 + in the server and mySQL.

Please search & post topic in forum for these kind of questions. (http://inoideas.org/)
I am closing this issue .

**Closed by inoerp** 2015-05-02 11:19 UTC

**Comment by rashedomar** [comment] 2017-04-20 11:49
i have same problem after install inoerp in wampserver at localhost , 
and when im login into inoerp and chose Arabic lang , inoerp system dose't Chang the lang , it still English.

**Comment by lextale** [comment] 2020-12-03 18:24
> i have same problem after install inoerp in wampserver at localhost ,
> and when im login into inoerp and chose Arabic lang , inoerp system dose't Chang the lang , it still English.

I have the same issue. However, I am choosing english but the page is translated in a mixture of english, german and greek. I begin to wonder if the problem is caused by my system's default language. I'm using Windows 10 in greek.
